### ISSUE TITLE
手册应该单独列出一个界面讲解 JS 插件？

### ISSUE THREAD

**Issue by FlameTEXT** [sealdice/sealdice-manual-next#179]
理由：

1. 相比于 JS 插件，牌堆和帮助文档的复杂度与 JS 插件不是一个等级的
2. “编写新的 TRPG 规则”这一节的内容在实际上也是编写一个 JS 插件，但是放在“编写 JS 插件”同级的界面中，不太合理

**Comment by JustAnotherID** [comment]
我的想法是把 cookbook 和 document 拆开。一节提供一个编写示例，另一节单列 API。

但改这个工作量可能有点大，慢慢来吧。
