### ISSUE TITLE
OpenShamrock部分是否重新写回手册

### ISSUE THREAD

**Issue by kenichiLyon** [sealdice/sealdice-manual-next#239]
rt。[OpenShamrock](https://github.com/whitechi73/OpenShamrock/releases/tag/1.1.1)近期仓库恢复public，同时发版1.1.1。里面包含OneBot分支的发布。core仓库已提issue(#497)。考虑到这样的情况，或许明确一下开发者的态度（继续支持/不继续支持）会好些

follow up。1.1.1版的OpenShamrock仍然存在支持OB的版本。（不同branch发了两个包）是否考虑写回手册？@JustAnotherID @Xiangze-Li @MX-fox

**Comment by MX-fox** [comment]
鉴于部署难度和 shamrock 近期行为，不建议写回手册，有需要的用户可参考归档后的教程自行部署。
