### ISSUE TITLE
归档整个基础知识一节，同时逐渐将部分部署指南直接指向上游的文档

### ISSUE THREAD

**Issue by JustAnotherID** [sealdice/sealdice-manual-next#246]
提议归档整个「基础知识」一章，并逐渐剥离部分部署指南内容。考虑如下：
1. 本手册是海豹的使用手册，介绍计算机使用内容超出了手册应当承担的内容，加重了手册维护的工作量。我们应当将更多精力放在完善手册中海豹本身使用内容的工作上。
2. 部署相关也应该逐渐引导向上游手册，由于QQ的特殊性，上游的部署方式可能频繁改变，我们可能很难做到实时更新，只有上游自己更清楚如何部署。如果有补充的部分可以直接向上游提交pr，而不是保留在我们的文档中。

cc @sealdice/manual-team 

补充：基础知识一块目前看起来并没有起到我们之前所期望的作用，不看的依然不会看。同时这一块除非维护成计算机百科全书，否则不可能完全覆盖，我们没有精力也不应该做这种事情。故提议归档降低压力。

**Comment by MintCider** [comment]
支持，拒绝保姆化。群内回答问题应做同样规范。但内置客户端未来的定位如何？

**Comment by MX-fox** [comment]
内置客户端是为了方便手机端用户以及小白用户使用，需要继续维护（阿巴阿巴）。
lagrange/llonebot/napcat/Chronocat归类于分离部署并且简单介绍连接方式后指路各个方案手册。

**Comment by JustAnotherID** [comment]
> 支持，拒绝保姆化。群内回答问题应做同样规范。但内置客户端未来的定位如何？

这个问题还是在core单开issue吧，这边只讨论手册的问题。

**Comment by kenichiLyon** [comment]
同意。此部分我稍后pr一个draft
